### ISSUE TITLE
ErrorException Client error: `GET https://translate.google.com/translate_a/single?

### ISSUE THREAD

**Issue by mmejaz** [Stichoza/google-translate-php#137]
ErrorException Client error: `GET https://translate.google.com/translate_a/single?client=webapp&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=auto&tl=ar&q=Home&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=595184.993166` resulted in a `429 Too Many Requests`.

Please guide me how can I fix this issue I don't know how can is use guzzle, please suggest me any blog are article, which is helpful to fix this issue.

**Comment by Stichoza** [comment]
Have you read the readme first?

**Comment by mmejaz** [comment]
yes, I install this package successfully, and this is works as per my requirements but doesn't know how can I use HTTP client configuration. Please guide me on how I can use it. it will be considered a great favor from your side.

**Comment by mmejaz** [comment]
because without using the HTTP client configuration, google block my IP address

**Comment by Stichoza** [comment]
Assuming you've read readme, you should know about [known limitations](https://github.com/Stichoza/google-translate-php#known-limitations), as well as [http client configuration](https://github.com/Stichoza/google-translate-php#http-client-configuration). In that section you'll find a link to docs of guzzle configuration docs. Guzzle docs will help you configure all you need.

Otherwise, configuring a Guzzle client is not related to this repository, feel free to post your question on stackoverflow.

**Comment by mmejaz** [comment]
can you please make a youtube video on it
