### ISSUE TITLE
Translate everything except dynamic variables/attributes?

### ISSUE THREAD

**Issue by 2K11CS12** [Stichoza/google-translate-php#167]
Hi,

How can I translate string having dynamic variables/attributes, something like below? 

`Here's your {{ value }} gift card for {{ shop }}!`

Just want to translate text which is not wrapped in curly braces.

any help/idea will be helpful!

Thanks

**Comment by ShpendBerisha** [comment]
According to [Google instructions](https://cloud.google.com/translate/faq#technical_questions), setting class="notranslate" prevents Google translation. So, for your question the only way is using css.

Here's your <span class="notranslate">{{ value }}l</span> gift card for <span class="notranslate">{{ shop}}l</span>!

**Comment by Stichoza** [comment]
I don't think it is possible through translating strings. The idea suggested by @ShpendBerisha won't work because Google will still translate text inside tags because it won't treat it as a webpage (The "notranslate" is used for translating webpages by link).

The only way I found is wrapping text inside < and > like this:

```
Here's your <{{value}}> gift card for <{{shop}}> !
```

Note that you should remove spaces between braces words.

P.S. I don't recommend relying on this because it might stop working at any time.
