### ISSUE TITLE
ErrorException (Client error: `GET https://translate.google.com/translate_a/single?)

### ISSUE THREAD

**Issue by mprince2k18** [Stichoza/google-translate-php#170]
HI,
I am using this library for so long, Suddenly face this error. http://prntscr.com/13mhaxj
I was working fine. I have no idea what just happened. Please help me to find out.
![image](https://user-images.githubusercontent.com/43857625/120160343-faa3b080-c217-11eb-88af-fcbc023465cc.png)

**Comment by frzsombor** [comment]
I can only see a part of the error message, but I think you are getting a _429 Too Many Requests_ error, which had been already mentioned in multiple issues and in the [Known Limitations](https://github.com/Stichoza/google-translate-php#known-limitations) of the readme. Please next time check the readme and search the issues before opening a new, also please don't open multiple issues for the same problem because you won't get a reply sooner anyway but making more work for the project owner.

**Comment by mprince2k18** [comment]
I fixed this by adding gtx instead of webapp
![image](https://user-images.githubusercontent.com/43857625/120172350-c2569f00-c224-11eb-9c26-8b22204743cf.png)
