### ISSUE TITLE
can i translate a Array  at one time?

### ISSUE THREAD

**Issue by vingoyuan** [Stichoza/google-translate-php#181]
i want to translate some words in one time . how to achieve it.

**Comment by Stichoza** [comment]
Each translation would require separate HTTP request, because Google Translate doesn't offer translating arrays. You can join strings as multiple sentences but it would not be accurate.

You can simply iterate over an array and translate each item, but be careful with [Google IP bans](https://github.com/Stichoza/google-translate-php#known-limitations).

P.S. sorry for late answer
