### ISSUE TITLE
Is there a way I can get Phonetic translation instead of Dictionary translations? 

### ISSUE THREAD

**Issue by Abhi150688** [Stichoza/google-translate-php#52]
I have a very specific usecase where I need phonetic translations instead of dictionary ones. Is there a way, the api can be customized for the same? 

Google translate does allow for phonetic translations as per article here: http://www.androidcentral.com/google-translate-app-gets-phonetic-support-more-languages

**Comment by Stichoza** [comment]
After merging #93 and fixing #89, you can use `getResponce()` method to get raw data from google. It contains phonetic translations in some cases. Mostly when you're translating a single word.

I'll push a v4.0.1 tag for this change

**Comment by Stichoza** [comment]
More details about pronunciations as it might help others.

By using `getResponse` method you can get the pronunciation. For example "sun" in Georgian is მზე (pronounced: mze). You can get this data like this:

```php
$tr = new GoogleTranslate('ka');
$res = $tr->getResponse('sun');
echo "Sun is pronounced: " . $res[0][1][2];
```

Result: `Sun is pronounced: mze`.

I've been avoiding adding this feature to this package as a separate method because the result containing the pronunciation is varying depending on the word/sentence translated.

For what it's worth I see results in `$res[0][1][2]`
