### ISSUE TITLE
Why now does it works only in localhost?

### ISSUE THREAD

**Issue by rignaneseleo** [Stichoza/google-translate-php#83]
Few versions ago, I've built this webtool stringsxmlbuilder.netsons.org and all worked.
Now the translation made by this tool doesn't work, but if I transfer the website on localhost and I run it with xampp it works well.

What could be? How can I debug it?

Thanks

**Comment by frzsombor** [comment]
Can you tell us what error do you get? Try trace the actual error message, because the problem could be anything. The first thing I can think about is that the IP of your server has been blacklisted by Google because of the automated usage, and now requires a captcha (which of course is not a supported thing in this library). And using your own computer with your home IP address is maybe not that suspicious to Google, so your IP is not blocked and you can use the translator from home. But that is just a guess based on my experience, first, you should find out the error.

**Comment by rignaneseleo** [comment]
Thanks for the reply.
I've changed the server and now works again.
Can you tell me where can I see the php error? I've the code surrounded 
between try/catch, have I to remove it?



In data 26 maggio 2017 17:01:23 Zsombor Franczia <notifications@github.com> 
ha scritto:

**Comment by frzsombor** [comment]
Sorry, but as long as I don't know anything about your project and I don't see your code in my editor, I can't tell you how and where you can catch your errors. But there are a lot of good articles about [PHP Exception handling](https://www.w3schools.com/php/php_exception.asp) on the web :)
